name: Calorie tracking workflow
on:
  schedule:
    - cron: "*/3 * * * *"  # Runs every 3 minutes
  workflow_dispatch:
jobs:
  track_calories:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install jinja2
          pip install pytz
   
      - name: Track daily calorie intake
        env:
            EMAIL_SENDER: ${{ secrets.EMAIL_SENDER }}
            EMAIL_RECIPIENT: ${{ secrets.EMAIL_RECIPIENT }}
            EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
            CALORIE_TARGET: 2000
        run: |
          python email_form.py
